### ISSUE TITLE
Count request with paginate 

### ISSUE THREAD

**Issue by goalia** [passionInfinite/mongoose-soft-delete#7]
When I try to use the plugin with mongoose paginate, I can’t found any record 😔

**Comment by passionInfinite** [comment]
Any steps to reproduce?

**Comment by goalia** [comment]
npm install mongoose-paginate-v2 
After try to make a request with something like this 
```js 
Model.paginate({}, { offset: 30, limit: 10 }, function(err, result) {
    // result.docs
    // result.totalPages
    // result.limit - 10
    // result.offset - 30
});
```
I have no record return from my database but the count (number of page, number of records) still works

**Comment by parth7676** [comment]
@Goal54 The package you have used is using find() to find all the data and then applying pagination on it. So, in that case, you will get all the non soft deleted records from your database.

The best way to solve your problem, for now, will be:
1. Remove the pagination package.
2. Use [express-paginate](https://github.com/expressjs/express-paginate).
3. And use our query methods. 

we are looking into pagination and will be available into next release.

**Comment by goalia** [comment]
I go into another way, no problem. Great to know it will be fix 😄
